apiVersion: cert-manager.io/v1
kind: {{ .Values.kind }}
metadata:
  name: {{ .Release.Name }}

  {{- if eq .Values.kind "Issuer" }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
spec:
  {{- if eq .Values.issuerType "selfSigned" }}
  selfSigned:
    {{- with .Values.selfSigneds }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}

  {{- if eq .Values.issuerType "ca" }}
  ca:
    {{- with .Values.ca }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}

  {{- if eq .Values.issuerType "vault" }}
  vault:
    {{- with .Values.vault }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}

  {{- if eq .Values.issuerType "venafi" }}
  venafi:
    {{- with .Values.venafi }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}

  {{- if eq .Values.issuerType "acme" }}  
  acme:
    {{- with .Values.acme }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  