apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: {{ .Values.selector }}
  servers:
  - hosts:
    {{- range .Values.hosts }}
    - {{ . | quote }}
    {{- end }}
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    {{- range .Values.hosts }}
    - {{ . | quote }}
    {{- end }}
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: {{ .Values.tls.mode }}
      {{- if eq .Values.tls.certType "default" }}
      privateKey: {{ .Values.tls.privateKey }}
      serverCertificate: {{ .Values.tls.serverCertificate }}
      {{- end }}

      {{- if eq .Values.tls.certType "credentials" }}
      credentialName: {{ .Values.tls.credentialName }} # fetches certs from Kubernetes secret
      {{- end }}
