apiVersion: v1
name: istio-virtual-service
version: 0.1.1
description: A Helm chart for creating an Istio VirtualService
keywords:
  - istio-virtualservice
  - virtualservice
  - istio
maintainers:
- name: "Ibraheem Al Saady"
  email: ibraheem.al-saady@outlook.com
engine: gotpl