host: something.domain.gq
# uncomment the line below if you need a type other than "http"
#type: tcp
# uncomment the line below if you need to specify a gateway. it will be absent if you do not have gateway:
#gateway: istio-system/ing-ingressgateway
endpoints:
  # include starting "/" at both the uri and rewriteUri
  # - uri: /service-uri # the uri the service should be reachable
  #   rewriteUri: / # the rewrite-uri for the service to match the actual service uri
  #   destinationPort: 80  # the port the kubernetes service is listening on, same as service.port?
  #   uriType: prefix # possible values are (prefix, exact, regex)
  #   destinationHost: # is the destination service name

  # example if no rewrite is needed
  #- uri: /service-uri2
  #  destinationPort: 80
 