apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ .Values.app.servicePort }}
    targetPort: {{ .Values.app.serviceTargetPort }}
  selector:
    app: {{ .Release.Name }}