apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  {{- if .Release.Name | hasSuffix "-virtualservice" }}
  name: {{ .Release.Name }}
  {{- else }}
  name: {{ .Release.Name }}-virtualservice
  {{- end }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "virtualservice.chart" . }}
spec:
  hosts:
  - {{ .Values.host }}
  {{- if .Values.gateway }}
  gateways:
  - {{ .Values.gateway }}
  {{- end }}
  {{- if .Values.type }}
  {{ .Values.type }}:
  {{- else }}
  http:
  {{- end }}
  {{- range .Values.endpoints }}
  - match:
    {{- if .uri }}
    - uri:
      {{- if .uriType }}
        {{ .uriType }}: {{ .uri }}
      {{- else}}
        prefix: {{ .uri }}
      {{- end}}
    {{- if .rewriteUri }}
    rewrite:
      uri: {{ .rewriteUri }}
    {{- end }}
    {{- end }}
    {{- if .port }}
    - port: {{ .port }}
    {{- end }}
    route:
    - destination:
        {{- if .destinationHost | hasSuffix ".com"}}
        host: {{ .destinationHost }}
        {{- else }}
        host: {{ .destinationHost }}.{{ $.Release.Namespace }}.svc.cluster.local
        {{- end }}
        port:
          number: {{ .destinationPort }}
  {{- end }}